# Generated by Django 5.2.4 on 2026-07-09 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0023_add_irradiance_to_monthlyconsumptionkpi'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailychartdata',
            name='daily_gross_consumption',
            field=models.FloatField(default=0.0, help_text='Consumo BRUTO diario en kWh (solo energía tomada de la red; inyección clampeada a 0).'),
        ),
        migrations.AddField(
            model_name='monthlyconsumptionkpi',
            name='total_gross_consumption_current_month',
            field=models.FloatField(default=0.0, help_text='Consumo BRUTO acumulado del mes actual en kWh (solo energía tomada de la red; inyección clampeada a 0).'),
        ),
        migrations.AddField(
            model_name='monthlyconsumptionkpi',
            name='total_gross_consumption_previous_month',
            field=models.FloatField(default=0.0, help_text='Consumo BRUTO acumulado del mes anterior en kWh (solo energía tomada de la red; inyección clampeada a 0).'),
        ),
        migrations.AlterField(
            model_name='dailychartdata',
            name='daily_consumption',
            field=models.FloatField(default=0.0, help_text='Consumo NETO diario en kWh (importación − exportación, net metering).'),
        ),
        migrations.AlterField(
            model_name='monthlyconsumptionkpi',
            name='total_consumption_current_month',
            field=models.FloatField(default=0.0, help_text='Consumo NETO acumulado del mes actual en kWh (importación − exportación, net metering).'),
        ),
        migrations.AlterField(
            model_name='monthlyconsumptionkpi',
            name='total_consumption_previous_month',
            field=models.FloatField(default=0.0, help_text='Consumo NETO acumulado del mes anterior en kWh (importación − exportación, net metering).'),
        ),
    ]
