# Generated by Django 5.2.4 on 2026-07-10 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0024_dailychartdata_daily_gross_consumption_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='electricmeterconsumption',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='electricmeterconsumption',
            name='device',
        ),
        migrations.RemoveField(
            model_name='electricmeterconsumption',
            name='institution',
        ),
        migrations.AlterUniqueTogether(
            name='electricmeterenergyconsumption',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='electricmeterenergyconsumption',
            name='device',
        ),
        migrations.RemoveField(
            model_name='electricmeterenergyconsumption',
            name='institution',
        ),
        migrations.DeleteModel(
            name='ElectricMeterChartData',
        ),
        migrations.DeleteModel(
            name='ElectricMeterConsumption',
        ),
        migrations.DeleteModel(
            name='ElectricMeterEnergyConsumption',
        ),
    ]
