# Generated by Django 5.2.16 on 2026-07-10 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0025_alter_electricmeterconsumption_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='electricmeterindicators',
            name='indicators__device__b7a3f3_idx',
        ),
        migrations.RemoveIndex(
            model_name='inverterchartdata',
            name='indicators__device__0e4683_idx',
        ),
        migrations.RemoveIndex(
            model_name='inverterindicators',
            name='indicators__device__4d678c_idx',
        ),
        migrations.RemoveIndex(
            model_name='weatherstationchartdata',
            name='indicators__device__e54e97_idx',
        ),
        migrations.RemoveIndex(
            model_name='weatherstationindicators',
            name='indicators__device__acd3a7_idx',
        ),
    ]
