# Generated by Django 5.2.16 on 2026-07-12 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0026_remove_electricmeterindicators_indicators__device__b7a3f3_idx_and_more'),
        ('scada_proxy', '0004_alter_invertermeasurement_device_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourlyInverterIndicators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.DateTimeField(help_text='Inicio de la hora del registro (aware, hora de Bogotá).')),
                ('energy_ac_kwh', models.FloatField(blank=True, default=0.0, help_text='Energía AC generada en la hora en kWh.', null=True)),
                ('energy_dc_kwh', models.FloatField(blank=True, default=0.0, help_text='Energía DC recibida en la hora en kWh.', null=True)),
                ('dc_ac_efficiency_pct', models.FloatField(blank=True, default=0.0, help_text='Eficiencia de conversión DC-AC de la hora en porcentaje.', null=True)),
                ('performance_ratio_pct', models.FloatField(blank=True, default=0.0, help_text='Performance Ratio de la hora en porcentaje.', null=True)),
                ('reference_energy_kwh', models.FloatField(blank=True, default=0.0, help_text='Energía de referencia de la hora en kWh.', null=True)),
                ('avg_power_w', models.FloatField(blank=True, default=0.0, help_text='Potencia promedio generada en la hora en W.', null=True)),
                ('max_power_w', models.FloatField(blank=True, default=0.0, help_text='Potencia máxima generada en la hora en W.', null=True)),
                ('min_power_w', models.FloatField(blank=True, default=0.0, help_text='Potencia mínima generada en la hora en W.', null=True)),
                ('avg_power_factor_pct', models.FloatField(blank=True, default=0.0, help_text='Factor de potencia promedio de la hora en porcentaje.', null=True)),
                ('avg_reactive_power_var', models.FloatField(blank=True, default=0.0, help_text='Potencia reactiva promedio de la hora en VAr.', null=True)),
                ('avg_apparent_power_va', models.FloatField(blank=True, default=0.0, help_text='Potencia aparente promedio de la hora en VA.', null=True)),
                ('avg_frequency_hz', models.FloatField(blank=True, default=0.0, help_text='Frecuencia promedio de la hora en Hz.', null=True)),
                ('frequency_stability_pct', models.FloatField(blank=True, default=0.0, help_text='Estabilidad de frecuencia de la hora en porcentaje.', null=True)),
                ('max_voltage_unbalance_pct', models.FloatField(blank=True, default=0.0, help_text='Desbalance máximo de tensión de la hora en porcentaje.', null=True)),
                ('max_current_unbalance_pct', models.FloatField(blank=True, default=0.0, help_text='Desbalance máximo de corriente de la hora en porcentaje.', null=True)),
                ('anomaly_score', models.FloatField(blank=True, default=0.0, help_text='Puntuación de anomalías de la hora (0-100, 0=sin anomalías).', null=True)),
                ('anomaly_details', models.JSONField(default=dict, help_text='Detalles de anomalías detectadas en la hora.')),
                ('measurement_count', models.IntegerField(default=0, help_text='Número de mediciones procesadas en la hora.')),
                ('calculated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora del cálculo.')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_inverter_indicators', to='scada_proxy.device')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_inverter_indicators', to='scada_proxy.institution')),
            ],
            options={
                'verbose_name': 'Indicadores Horarios de Inversor',
                'verbose_name_plural': 'Indicadores Horarios de Inversores',
                'indexes': [models.Index(fields=['device', 'hour'], name='indicators__device__015c68_idx'), models.Index(fields=['institution', 'hour'], name='indicators__institu_f9666f_idx'), models.Index(fields=['hour'], name='indicators__hour_b917a9_idx')],
                'unique_together': {('device', 'hour')},
            },
        ),
        migrations.CreateModel(
            name='HourlyMeterIndicators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.DateTimeField(help_text='Inicio de la hora del registro (aware, hora de Bogotá).')),
                ('imported_energy_kwh', models.FloatField(blank=True, default=0.0, help_text='Energía importada en la hora en kWh.', null=True)),
                ('exported_energy_kwh', models.FloatField(blank=True, default=0.0, help_text='Energía exportada en la hora en kWh.', null=True)),
                ('net_energy_consumption_kwh', models.FloatField(blank=True, default=0.0, help_text='Energía neta consumida en la hora en kWh.', null=True)),
                ('peak_demand_kw', models.FloatField(blank=True, default=0.0, help_text='Demanda pico de la hora en kW.', null=True)),
                ('avg_demand_kw', models.FloatField(blank=True, default=0.0, help_text='Demanda promedio de la hora en kW.', null=True)),
                ('load_factor_pct', models.FloatField(blank=True, default=0.0, help_text='Factor de carga de la hora en porcentaje.', null=True)),
                ('avg_power_factor', models.FloatField(blank=True, default=0.0, help_text='Factor de potencia promedio de la hora.', null=True)),
                ('max_voltage_unbalance_pct', models.FloatField(blank=True, default=0.0, help_text='Desbalance máximo de tensión de la hora en porcentaje.', null=True)),
                ('max_current_unbalance_pct', models.FloatField(blank=True, default=0.0, help_text='Desbalance máximo de corriente de la hora en porcentaje.', null=True)),
                ('max_voltage_thd_pct', models.FloatField(blank=True, default=0.0, help_text='THD máximo de tensión de la hora en porcentaje.', null=True)),
                ('max_current_thd_pct', models.FloatField(blank=True, default=0.0, help_text='THD máximo de corriente de la hora en porcentaje.', null=True)),
                ('max_current_tdd_pct', models.FloatField(blank=True, default=0.0, help_text='TDD máximo de corriente de la hora en porcentaje.', null=True)),
                ('measurement_count', models.IntegerField(default=0, help_text='Número de mediciones procesadas en la hora.')),
                ('calculated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora del cálculo.')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_meter_indicators', to='scada_proxy.device')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_meter_indicators', to='scada_proxy.institution')),
            ],
            options={
                'verbose_name': 'Indicadores Horarios de Medidor Eléctrico',
                'verbose_name_plural': 'Indicadores Horarios de Medidores Eléctricos',
                'indexes': [models.Index(fields=['device', 'hour'], name='indicators__device__eaa591_idx'), models.Index(fields=['institution', 'hour'], name='indicators__institu_48f446_idx'), models.Index(fields=['hour'], name='indicators__hour_dbaf1f_idx')],
                'unique_together': {('device', 'hour')},
            },
        ),
        migrations.CreateModel(
            name='HourlyWeatherIndicators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.DateTimeField(help_text='Inicio de la hora del registro (aware, hora de Bogotá).')),
                ('avg_irradiance_wm2', models.FloatField(blank=True, default=0.0, help_text='Irradiancia promedio de la hora en W/m² (filtrada 06-18h, 0-1100).', null=True)),
                ('irradiance_energy_kwh_m2', models.FloatField(blank=True, default=0.0, help_text='Irradiancia acumulada de la hora en kWh/m².', null=True)),
                ('avg_temperature_c', models.FloatField(blank=True, default=0.0, help_text='Temperatura promedio de la hora en °C.', null=True)),
                ('max_temperature_c', models.FloatField(blank=True, default=0.0, help_text='Temperatura máxima de la hora en °C.', null=True)),
                ('min_temperature_c', models.FloatField(blank=True, default=0.0, help_text='Temperatura mínima de la hora en °C.', null=True)),
                ('avg_humidity_pct', models.FloatField(blank=True, default=0.0, help_text='Humedad relativa promedio de la hora en %.', null=True)),
                ('avg_wind_speed_kmh', models.FloatField(blank=True, default=0.0, help_text='Velocidad media del viento de la hora en km/h.', null=True)),
                ('avg_wind_direction_deg', models.FloatField(blank=True, default=0.0, help_text='Dirección promedio del viento de la hora en grados (promedio aritmético).', null=True)),
                ('precipitation_cm', models.FloatField(blank=True, default=0.0, help_text='Precipitación de la hora en cm (último valor del acumulador).', null=True)),
                ('measurement_count', models.IntegerField(default=0, help_text='Número de mediciones procesadas en la hora.')),
                ('calculated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora del cálculo.')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_weather_indicators', to='scada_proxy.device')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_weather_indicators', to='scada_proxy.institution')),
            ],
            options={
                'verbose_name': 'Indicadores Horarios de Estación Meteorológica',
                'verbose_name_plural': 'Indicadores Horarios de Estaciones Meteorológicas',
                'indexes': [models.Index(fields=['device', 'hour'], name='indicators__device__204c10_idx'), models.Index(fields=['institution', 'hour'], name='indicators__institu_9e945d_idx'), models.Index(fields=['hour'], name='indicators__hour_44e175_idx')],
                'unique_together': {('device', 'hour')},
            },
        ),
    ]
