# Generated by Django 5.2.4 on 2026-07-10 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scada_proxy', '0002_invertermeasurement_measurementsyncchunk_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Measurement',
        ),
    ]
