# Generated by Django 5.2.16 on 2026-07-10 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scada_proxy', '0003_delete_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invertermeasurement',
            name='device',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='inverter_measurements', to='scada_proxy.device'),
        ),
        migrations.AlterField(
            model_name='metermeasurement',
            name='device',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='meter_measurements', to='scada_proxy.device'),
        ),
        migrations.AlterField(
            model_name='weatherstationmeasurement',
            name='device',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='weather_measurements', to='scada_proxy.device'),
        ),
    ]
